import React from "react";

const TermsAndCondition: React.FC = () => {
    const sections = [
        {
            title: "1. Services Offered:",
            content: "Our website offers financial advice and guidance services to clients who are seeking to achieve their financial goals. Our services are fee-only, which means that we do not receive any commissions or other forms of compensation from third-party companies or financial products.",
        },
        {
            title: "2. Client Agreement:",
            content: "In order to use our services, you must first sign our client agreement, complete your KYC, and fill in the risk profile questionnaire. This agreement outlines the scope of our services, our fees, and our responsibilities to you as a client.",
        },
        {
            title: "3. Confidentiality:",
            content: "We understand the importance of keeping your financial information confidential. We will not disclose your personal or financial information to any third parties unless required by law or with your written permission or as mentioned in the privacy policy. Whilst we do take adequate measures to safeguard your information, we do not take responsibility for your information in case of a security breach at these service providers or in case you share your login information with anyone or if your social media account was to get hacked.",
        },
        {
            title: "4. Investment Advice:",
            content: "Our website may contain general information about investment strategies, but this information should not be considered personalized investment advice. Before making any investment decisions, you should consult with a licensed financial advisor.",
        },
        {
            title: "5. No Guarantee of Results:",
            content: "While we strive to provide our clients with the best possible financial advice and guidance, we cannot guarantee that our recommendations will result in any specific investment outcomes or financial results. We will not be responsible for any losses or damages that may result from your investment decisions.",
        },
        {
            title: "6. Limitations of Liability:",
            content: "We will not be liable for any damages arising from the use of our website or our services, including but not limited to direct, indirect, incidental, or consequential damages. You acknowledge that our liability is limited to the fees paid by you for our services.",
        },
        {
            title: "7. Termination:",
            content: "We reserve the right to terminate our services to any client at any time, for any reason. We will provide you with written notice of termination, and any fees paid for services not yet rendered will be refunded to you.",
        },
        {
            title: "8. Changes to Terms and Conditions:",
            content: "We may update these terms and conditions at any time, without prior notice. Your continued use of our website and services after any such changes will constitute your acceptance of the revised terms and conditions.",
        },
        {
            title: "9. Intellectual Property:",
            content: "Our website and all of its content, including but not limited to text, graphics, logos, and images, are the property of our company and are protected by copyright and other intellectual property laws. You may not use or reproduce any content from our website without our written permission.",
        },
        {
            title: "10. Governing Law:",
            content: "In case of any dispute, either judicial or quasi-judicial, the same will be subject to the exclusive jurisdiction of the courts in Mumbai. These terms shall be construed in accordance with the laws prevalent in India and are subject to SEBI guidelines, circulars, press releases, or notifications that may be issued by SEBI from time to time or the Government of India, to regulate the activities of RIAs (Registered Investment Advisors).",
        },
    ];

    return (
        <>
            <div className="p-6 w-full sm:w-[90%] md:w-[80%] xl:w-[70%] m-auto font-[500] text-[#000000d9]">
                Thank you for selecting the Investment Advisory Services offered by PLNR INVESTMENT ADVISORS (SEBI Registered Investment Adviser – INA 000018966) through their website (hereinafter referred to as " PLNR ") via its website www.plnr.in.
                This document is an electronic record, being generated by a computer system and it does not require any physical or digital signature. This document is published in accordance with Information Technology guidelines for intermediaries and contains the rules and regulations for accessing and using PLNR.
                <p className="font-[300] mt-4">
                    Please carefully examine these Terms and Conditions. By continuing, and accepting through electronic means
                     (such as clicking "I Agree"), either by accessing the website using your login credentials or utilizing the Services, you are consenting to these Terms and Conditions.
                    Access to and use of the Services may only be granted upon acceptance of these terms and conditions.
                </p>   
            </div>
            <div className="p-6 w-full sm:w-[90%] md:w-[80%] xl:w-[70%] m-auto">
                {sections.map((section, index) => (
                    <div
                        key={index}
                        className="flex items-start text-[14px] leading-[22px] text-black/85  mb-4"
                    >
                        <span className="font-[300] text-[16px] leading-[26px]">{section.title} {section.content}</span>

                    </div>
                ))}
            </div>
        </>
    );
};

export default TermsAndCondition;
